
services:
  app:
    build: .
    #image: gometeo:latest
    restart: always
    networks:
      - traefik
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-lan"
      - "traefik.http.routers.to-gometeo.rule=Host(`gometeo.vintz.fr`)"
      - "traefik.http.routers.to-gometeo.tls.certresolver=vintz-wildcard"
      - "traefik.http.routers.to-gometeo.tls.domains[0].main=*.vintz.fr"  
      - "traefik.http.services.gometeo.loadbalancer.server.port=1051"

networks:
  traefik:
    name: "traefik-lan"
    external: true
