entryPoints:
  web:
    address: "127.0.0.1:1051"

providers:
  docker:
    exposedByDefault: false
    network: gometeo-dev

log:
  level: INFO

accessLog: {}

api:
  dashboard: true
  insecure: true
